{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "skillcenter.fullname" . }}-api
  labels:
    {{- include "skillcenter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "skillcenter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
