export const ROLES = {
  developer: {
    label: "普通开发者",
    actorRole: "developer",
    userId: "developer-user",
    navigation: ["market", "my-skills", "upload"],
    canUpload: true,
    canReview: false,
  },
  admin: {
    label: "平台管理员",
    actorRole: "admin",
    userId: "platform-admin",
    navigation: ["market", "my-skills", "upload", "review", "analytics", "quality", "exports", "operations", "settings"],
    canUpload: true,
    canReview: true,
  },
};

export const NAV_ITEMS = [
  { id: "market", label: "技能市场", icon: "storefront" },
  { id: "my-skills", label: "技能合集", icon: "squares-four" },
  { id: "upload", label: "发布 Skill", icon: "upload-simple" },
  { id: "review", label: "待审核技能", icon: "clipboard-text" },
  { id: "analytics", label: "技能统计", icon: "chart-line-up" },
  { id: "quality", label: "质量管理", icon: "shield-check" },
  { id: "exports", label: "审计与导出", icon: "file-arrow-down" },
  { id: "operations", label: "运行监控", icon: "pulse" },
  { id: "settings", label: "标签管理", icon: "tag" },
];

export const SKILLS = [
  {
    id: "eox-query",
    name: "EOX查询Skill",
    version: "v1.2.0",
    description: "根据自然语言查询设备 EOX 状态，支持 EOM / EOP / EOS 分析与统计",
    category: "网络运维",
    tags: ["网络运维", "只读查询"],
    risk: "低风险",
    riskTone: "low",
    team: "网络智能团队",
    owner: "网络智能团队",
    icon: "magnifying-glass",
    iconTone: "blue",
    rating: 4.8,
    reviews: 76,
    calls: 12500,
    installs: 680,
    favorites: 235,
    status: "稳定",
    lastUpdated: "2026-08-10",
    publishedAt: "2026-06-30",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "只读取而非权限",
    capabilities: [
      "支持自然语言：通过自然语言查询平台设备的 EOM / EOP / EOS 状态",
      "批量设备查询：支持按设备列表或条件批量查询生命周期状态",
      "EOX统计分析：提供 EOM / EOP / EOS 统计分析与趋势展示",
      "生命周期风险识别：识别即将 EOS 的设备并给出风险提醒",
    ],
    suitableFor: ["网络巡检", "网络规划", "生命周期管理", "设备合规性审计"],
    unsuitableFor: ["设备配置修改", "生产变更", "涉及写入操作的任务"],
    value: "EOX查询Skill 帮助运维与管理团队快速掌握设备生命周期状态，降低因设备 EOS 带来的业务中断风险，支持数据驱动的网络规划与预算管理。",
    exampleInput: "查询北京园区所有硬件 EOS 设备",
    exampleOutput: "发现35台设备，其中EOS设备8台，建议制定替换计划。",
    collection: ["网络运维助手合集", "通用Agent能力包"],
  },
  {
    id: "data-analyst",
    name: "数据分析助手",
    version: "v1.1.0",
    description: "将业务数据转化为可追踪的分析结论、图表与下一步行动建议",
    category: "效率工具",
    tags: ["数据分析", "只读查询"],
    risk: "低风险",
    riskTone: "low",
    team: "开发效能团队",
    owner: "开发效能团队",
    icon: "chart-bar",
    iconTone: "green",
    rating: 4.7,
    reviews: 54,
    calls: 9240,
    installs: 520,
    favorites: 189,
    status: "稳定",
    lastUpdated: "2026-08-08",
    publishedAt: "2026-07-12",
    language: "Python",
    supportedLanguage: "中文 / English",
    permissionSummary: "读取分析数据，不修改源数据",
    capabilities: ["读取 CSV、JSON 与表格数据并识别指标", "自动生成趋势、异常与分群结论", "输出可复用的分析摘要和后续行动建议"],
    suitableFor: ["迭代复盘", "质量分析", "指标周报"],
    unsuitableFor: ["在线修改源数据", "替代财务审批", "处理未脱敏敏感数据"],
    value: "把重复的数据整理工作交给 Skill，将更多时间留给问题判断和方案决策。",
    exampleInput: "分析本周构建失败率和主要失败原因",
    exampleOutput: "失败率较上周下降 12%，主要问题集中在依赖缓存失效。",
    collection: ["工程效率工具箱", "通用Agent能力包"],
  },
  {
    id: "ppt-generator",
    name: "PPT生成Skill",
    version: "v1.0.0",
    description: "根据主题和内容自动生成专业、美观的汇报型 PPT",
    category: "效率工具",
    tags: ["方案设计", "内容生成"],
    risk: "低风险",
    riskTone: "low",
    team: "方案智能团队",
    owner: "方案智能团队",
    icon: "presentation-chart",
    iconTone: "orange",
    rating: 4.5,
    reviews: 39,
    calls: 7320,
    installs: 455,
    favorites: 168,
    status: "稳定",
    lastUpdated: "2026-08-06",
    publishedAt: "2026-07-04",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取输入内容，生成本地文件",
    capabilities: ["根据大纲生成页面结构", "匹配企业汇报版式和视觉层级", "支持导出 PPTX 并保留页面备注"],
    suitableFor: ["技术汇报", "项目周报", "方案评审"],
    unsuitableFor: ["替代正式品牌审核", "直接发布未经确认的结论"],
    value: "以统一的汇报结构降低制作成本，让团队快速复用成熟的内容表达方式。",
    exampleInput: "把本次版本复盘整理成 8 页汇报材料",
    exampleOutput: "已生成包含背景、数据、问题、方案和行动项的 PPTX。",
    collection: ["方案设计工具箱", "通用Agent能力包"],
  },
  {
    id: "config-check",
    name: "配置检查Skill",
    version: "v1.1.0",
    description: "检查设备配置合规性，识别风险配置并提供修复建议",
    category: "网络运维",
    tags: ["网络运维", "合规检查"],
    risk: "中风险",
    riskTone: "medium",
    team: "网络智能团队",
    owner: "网络智能团队",
    icon: "shield-check",
    iconTone: "blue",
    rating: 4.6,
    reviews: 48,
    calls: 8230,
    installs: 520,
    favorites: 189,
    status: "稳定",
    lastUpdated: "2026-08-01",
    publishedAt: "2026-06-20",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取配置并输出建议，不自动修改设备",
    capabilities: ["按规则集检查配置", "给出风险等级与修复建议", "输出审计记录"],
    suitableFor: ["变更前检查", "安全审计"],
    unsuitableFor: ["自动执行修复", "无审批的生产操作"],
    value: "通过标准化规则降低配置检查遗漏，帮助维护者把高风险动作留在审批链中。",
    exampleInput: "检查这批交换机是否符合部门基线",
    exampleOutput: "发现 3 条中风险配置，已生成修复建议清单。",
    collection: ["网络运维助手合集"],
  },
  {
    id: "fault-locator",
    name: "故障定位Skill",
    version: "v1.3.0",
    description: "智能分析告警和日志，快速定位网络故障根因",
    category: "网络运维",
    tags: ["网络运维", "故障分析"],
    risk: "中风险",
    riskTone: "medium",
    team: "运维智能团队",
    owner: "运维智能团队",
    icon: "magnifying-glass",
    iconTone: "purple",
    rating: 4.9,
    reviews: 82,
    calls: 15680,
    installs: 732,
    favorites: 312,
    status: "稳定",
    lastUpdated: "2026-07-29",
    publishedAt: "2026-06-10",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取告警和日志，不执行变更",
    capabilities: ["聚合多源告警", "结合拓扑识别影响范围", "形成根因与排查路径"],
    suitableFor: ["故障值守", "网络巡检"],
    unsuitableFor: ["直接执行修复脚本", "跳过变更审批"],
    value: "把故障信息整理成可执行的排查路径，帮助值班团队缩短定位时间。",
    exampleInput: "分析核心交换机的链路抖动告警",
    exampleOutput: "初步定位为上联光模块异常，建议优先检查端口 1/0/48。",
    collection: ["网络运维助手合集"],
  },
  {
    id: "test-case-generator",
    name: "测试用例生成Skill",
    version: "v1.2.0",
    description: "根据需求和接口自动生成测试用例，覆盖多种场景",
    category: "测试管理",
    tags: ["测试管理", "质量保障"],
    risk: "低风险",
    riskTone: "low",
    team: "测试智能团队",
    owner: "测试智能团队",
    icon: "check-square",
    iconTone: "green",
    rating: 4.6,
    reviews: 43,
    calls: 9860,
    installs: 612,
    favorites: 276,
    status: "稳定",
    lastUpdated: "2026-07-27",
    publishedAt: "2026-06-16",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取需求和接口文档，输出测试文件",
    capabilities: ["从需求提取验收条件", "覆盖正常、异常与边界场景", "生成可导入测试管理工具的文件"],
    suitableFor: ["接口测试", "回归测试"],
    unsuitableFor: ["替代测试评审", "自动修改生产数据"],
    value: "让测试设计从模板和经验中解放出来，提升质量团队的覆盖速度。",
    exampleInput: "为用户登录接口生成边界测试用例",
    exampleOutput: "已生成 24 条测试用例，覆盖鉴权、限流和异常输入。",
    collection: ["测试效能工具箱"],
  },
  {
    id: "code-generator",
    name: "代码生成Skill",
    version: "v2.0.0",
    description: "根据需求生成高质量代码，支持多种编程语言与团队规范",
    category: "研发开发",
    tags: ["研发开发", "代码生成"],
    risk: "低风险",
    riskTone: "low",
    team: "研发效能团队",
    owner: "研发效能团队",
    icon: "code",
    iconTone: "blue",
    rating: 4.7,
    reviews: 66,
    calls: 18920,
    installs: 890,
    favorites: 421,
    status: "稳定",
    lastUpdated: "2026-07-26",
    publishedAt: "2026-05-18",
    language: "TypeScript",
    supportedLanguage: "中文 / English",
    permissionSummary: "读取需求，输出代码文件",
    capabilities: ["从需求提取接口和数据结构", "按团队规范生成代码", "提供可运行的测试样例"],
    suitableFor: ["样板代码", "接口开发"],
    unsuitableFor: ["直接合入生产分支", "跳过代码评审"],
    value: "让团队更快从想法进入可评审的实现阶段。",
    exampleInput: "为订单查询接口生成 TypeScript 服务层",
    exampleOutput: "已生成接口、类型定义和单元测试样例。",
    collection: ["研发效能工具箱"],
  },
  {
    id: "topology-analysis",
    name: "拓扑分析Skill",
    version: "v1.1.0",
    description: "分析网络拓扑结构，提供优化建议和可视化展示",
    category: "网络运维",
    tags: ["网络规划", "拓扑分析"],
    risk: "中风险",
    riskTone: "medium",
    team: "网络规划团队",
    owner: "网络规划团队",
    icon: "graph",
    iconTone: "blue",
    rating: 4.7,
    reviews: 40,
    calls: 6540,
    installs: 398,
    favorites: 142,
    status: "稳定",
    lastUpdated: "2026-07-23",
    publishedAt: "2026-06-02",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取拓扑数据并输出分析",
    capabilities: ["识别关键链路和单点风险", "生成拓扑摘要", "提供容量优化建议"],
    suitableFor: ["网络规划", "扩容评估"],
    unsuitableFor: ["自动调整网络设备", "替代架构评审"],
    value: "让复杂的拓扑关系更容易被团队看懂和讨论。",
    exampleInput: "分析园区网络的关键链路",
    exampleOutput: "识别出 2 条高负载链路，建议安排扩容评估。",
    collection: ["网络运维助手合集"],
  },
  {
    id: "requirement-analysis",
    name: "需求分析Skill",
    version: "v1.3.0",
    description: "智能分析需求文档，提取关键信息和业务规则",
    category: "研发开发",
    tags: ["研发开发", "需求分析"],
    risk: "低风险",
    riskTone: "low",
    team: "需求智能团队",
    owner: "需求智能团队",
    icon: "chats-circle",
    iconTone: "purple",
    rating: 4.8,
    reviews: 58,
    calls: 11230,
    installs: 573,
    favorites: 203,
    status: "稳定",
    lastUpdated: "2026-07-21",
    publishedAt: "2026-05-27",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取需求文档，输出分析摘要",
    capabilities: ["提取角色、场景和验收条件", "识别歧义与缺失信息", "生成需求评审清单"],
    suitableFor: ["需求澄清", "评审准备"],
    unsuitableFor: ["代替业务确认", "直接修改基线需求"],
    value: "用结构化摘要减少需求沟通中的信息损耗。",
    exampleInput: "分析这份版本需求的验收范围",
    exampleOutput: "已整理 12 条验收条件并标记 3 个待确认问题。",
    collection: ["研发效能工具箱"],
  },
  {
    id: "log-analysis",
    name: "日志分析Skill",
    version: "v1.2.0",
    description: "智能分析系统日志，识别异常模式和潜在问题",
    category: "网络运维",
    tags: ["网络运维", "故障分析"],
    risk: "中风险",
    riskTone: "medium",
    team: "运维智能团队",
    owner: "运维智能团队",
    icon: "database",
    iconTone: "orange",
    rating: 4.6,
    reviews: 51,
    calls: 8910,
    installs: 487,
    favorites: 156,
    status: "稳定",
    lastUpdated: "2026-07-20",
    publishedAt: "2026-05-19",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取日志并输出分析报告",
    capabilities: ["聚合相似错误", "识别异常峰值", "输出排查建议"],
    suitableFor: ["值班排障", "稳定性分析"],
    unsuitableFor: ["直接执行修复", "存储未脱敏日志"],
    value: "将分散的日志线索组织成可跟进的问题列表。",
    exampleInput: "分析昨夜服务重启期间的错误日志",
    exampleOutput: "发现 4 类异常，其中 1 类与依赖服务超时相关。",
    collection: ["网络运维助手合集"],
  },
  {
    id: "test-report",
    name: "测试报告生成Skill",
    version: "v1.1.0",
    description: "自动生成测试执行报告，支持多种格式输出",
    category: "测试管理",
    tags: ["测试管理", "质量保障"],
    risk: "低风险",
    riskTone: "low",
    team: "测试智能团队",
    owner: "测试智能团队",
    icon: "clipboard-text",
    iconTone: "green",
    rating: 4.4,
    reviews: 35,
    calls: 5820,
    installs: 341,
    favorites: 98,
    status: "稳定",
    lastUpdated: "2026-07-18",
    publishedAt: "2026-06-01",
    language: "Python",
    supportedLanguage: "中文",
    permissionSummary: "读取测试结果并生成报告",
    capabilities: ["汇总通过率和缺陷", "生成趋势图表", "支持 Markdown 与 XLSX 输出"],
    suitableFor: ["迭代结项", "质量周报"],
    unsuitableFor: ["替代测试结论确认", "修改原始结果"],
    value: "把测试数据快速整理成团队可读、可追踪的质量报告。",
    exampleInput: "生成本次回归测试报告",
    exampleOutput: "已生成包含通过率、缺陷分布和风险项的报告。",
    collection: ["测试效能工具箱"],
  },
  {
    id: "knowledge-qa",
    name: "知识问答Skill",
    version: "v2.1.0",
    description: "基于内部知识库提供准确、可追溯的问答",
    category: "通用工具",
    tags: ["通用工具", "知识问答"],
    risk: "低风险",
    riskTone: "low",
    team: "知识管理团队",
    owner: "知识管理团队",
    icon: "brain",
    iconTone: "purple",
    rating: 4.9,
    reviews: 91,
    calls: 22150,
    installs: 1023,
    favorites: 567,
    status: "稳定",
    lastUpdated: "2026-07-16",
    publishedAt: "2026-05-06",
    language: "Python",
    supportedLanguage: "中文 / English",
    permissionSummary: "读取已授权知识库，不写入源文档",
    capabilities: ["引用内部知识来源", "标记答案置信度", "在无答案时明确说明"],
    suitableFor: ["流程查询", "研发知识检索"],
    unsuitableFor: ["替代正式制度解释", "读取未授权资料"],
    value: "让分散在文档、规范和经验中的知识更容易被找到。",
    exampleInput: "查询部门的版本发布流程",
    exampleOutput: "已返回流程步骤、责任人和相关文档链接。",
    collection: ["通用Agent能力包"],
  },
];

export const PLATFORM_METRICS = [
  { label: "技能总数", value: 128, delta: "较上月 ↑16", tone: "blue" },
  { label: "调用总次数", value: 128560, delta: "较上月 ↑23.5%", tone: "green" },
  { label: "收藏总数", value: 12860, delta: "较上月 ↑18.2%", tone: "green" },
  { label: "安装总数", value: 8920, delta: "较上月 ↑28.2%", tone: "green" },
];

export const INVOCATION_SERIES = [
  { day: "08-11", calls: 4380, success: 96.8 },
  { day: "08-12", calls: 5120, success: 97.2 },
  { day: "08-13", calls: 4760, success: 96.4 },
  { day: "08-14", calls: 5840, success: 98.1 },
  { day: "08-15", calls: 6120, success: 98.4 },
  { day: "08-16", calls: 6490, success: 98.8 },
  { day: "08-17", calls: 6810, success: 98.6 },
];

export function filterSkills(skills, { query = "", category = "all" } = {}) {
  const normalizedQuery = query.trim().toLowerCase();
  return skills.filter((skill) => {
    const matchesCategory = category === "all" || skill.category === category;
    const searchable = [skill.name, skill.description, skill.owner, ...skill.tags].join(" ").toLowerCase();
    return matchesCategory && (!normalizedQuery || searchable.includes(normalizedQuery));
  });
}

export function getNavigationForRole(role) {
  return ROLES[role]?.navigation ?? ROLES.developer.navigation;
}

export const MARKET_SORT_OPTIONS = [
  { value: "downloads", label: "最多下载" },
  { value: "calls", label: "最多调用" },
  { value: "favorites", label: "最多收藏" },
  { value: "updated", label: "最近更新" },
];

export function sortSkills(skills, sort = "updated") {
  const metric = {
    downloads: (skill) => Number(skill.installs ?? skill.metrics?.installs ?? 0),
    calls: (skill) => Number(skill.calls ?? skill.metrics?.calls ?? 0),
    favorites: (skill) => Number(skill.favorites ?? skill.metrics?.favorites ?? 0),
    updated: (skill) => Date.parse(skill.lastUpdated ?? skill.updatedAt ?? skill.publishedAt ?? "") || 0,
  }[sort] ?? ((skill) => Date.parse(skill.lastUpdated ?? skill.updatedAt ?? skill.publishedAt ?? "") || 0);
  return skills.map((skill, index) => ({ skill, index })).sort((left, right) => metric(right.skill) - metric(left.skill) || left.index - right.index).map(({ skill }) => skill);
}

export function paginateItems(items, page = 1, pageSize = 12) {
  const safePage = Math.max(1, Number(page) || 1);
  const safePageSize = Math.max(1, Number(pageSize) || 12);
  return items.slice((safePage - 1) * safePageSize, safePage * safePageSize);
}

export const EXAMPLE_COLLECTIONS = [
  {
    collectionId: "example-network",
    name: "网络运维助手合集",
    description: "覆盖查询、配置检查、故障定位和拓扑分析的网络运维能力。",
    ownerTeamId: "network-intelligence",
    visibility: "public",
    skillIds: ["eox-query", "config-check", "fault-locator", "topology-analysis"],
    sortOrder: 10,
    status: "published",
  },
  {
    collectionId: "example-engineering",
    name: "研发效能工具箱",
    description: "从需求分析、代码生成到测试用例，支持研发团队高效交付。",
    ownerTeamId: "dev-efficiency",
    visibility: "public",
    skillIds: ["requirement-analysis", "code-generator", "test-case-generator"],
    sortOrder: 20,
    status: "published",
  },
];

export function getSkillById(id) {
  return SKILLS.find((skill) => skill.id === id);
}

export function formatMetric(value) {
  return new Intl.NumberFormat("zh-CN").format(value);
}

export function formatMarketTitle(total) {
  return `浏览 ${formatMetric(total)} 个 Skill`;
}

export function getCollectionSkillCount(collection) {
  return collection?.skills?.length ?? collection?.skillIds?.length ?? 0;
}

export function filterCollections(collections, { query = "" } = {}) {
  const normalizedQuery = query.trim().toLowerCase();
  if (!normalizedQuery) return collections;
  return collections.filter((collection) => [collection.name, collection.description, collection.ownerTeamId, ...(collection.tags ?? [])].filter(Boolean).join(" ").toLowerCase().includes(normalizedQuery));
}

export function sortCollections(collections, sort = "updated") {
  const metric = {
    downloads: (collection) => Number(collection.downloads ?? collection.metrics?.downloads ?? 0),
    calls: (collection) => Number(collection.calls ?? collection.metrics?.calls ?? 0),
    favorites: (collection) => Number(collection.favorites ?? collection.metrics?.favorites ?? 0),
    updated: (collection) => Date.parse(collection.lastUpdated ?? collection.updatedAt ?? collection.createdAt ?? collection.publishedAt ?? "") || 0,
  }[sort] ?? ((collection) => Date.parse(collection.lastUpdated ?? collection.updatedAt ?? collection.createdAt ?? collection.publishedAt ?? "") || 0);
  return collections.map((collection, index) => ({ collection, index })).sort((left, right) => metric(right.collection) - metric(left.collection) || left.index - right.index).map(({ collection }) => collection);
}
